version: '3'

services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./playground:/home/jovyan/notebooks/playground"
      - "./data:/home/jovyan/data"
    ports:
      - "8888:8888"
    environment:
      - GRANT_SUDO=yes
